
package com.ofss.fcubs.gw.ws.types;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FCUBSCustomerService", targetNamespace = "http://types.ws.gw.fcubs.ofss.com", wsdlLocation = "http://10.0.0.59:7005/FCUBSCustomerService/FCUBSCustomerService?wsdl")
public class FCUBSCustomerService
    extends Service
{

    private final static URL FCUBSCUSTOMERSERVICE_WSDL_LOCATION;
    private final static WebServiceException FCUBSCUSTOMERSERVICE_EXCEPTION;
    private final static QName FCUBSCUSTOMERSERVICE_QNAME = new QName("http://types.ws.gw.fcubs.ofss.com", "FCUBSCustomerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.0.59:7005/FCUBSCustomerService/FCUBSCustomerService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FCUBSCUSTOMERSERVICE_WSDL_LOCATION = url;
        FCUBSCUSTOMERSERVICE_EXCEPTION = e;
    }

    public FCUBSCustomerService() {
        super(__getWsdlLocation(), FCUBSCUSTOMERSERVICE_QNAME);
    }

    public FCUBSCustomerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FCUBSCUSTOMERSERVICE_QNAME, features);
    }

    public FCUBSCustomerService(URL wsdlLocation) {
        super(wsdlLocation, FCUBSCUSTOMERSERVICE_QNAME);
    }

    public FCUBSCustomerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FCUBSCUSTOMERSERVICE_QNAME, features);
    }

    public FCUBSCustomerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FCUBSCustomerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FCUBSCustomerServiceSEI
     */
    @WebEndpoint(name = "FCUBSCustomerServiceSEI")
    public FCUBSCustomerServiceSEI getFCUBSCustomerServiceSEI() {
        return super.getPort(new QName("http://types.ws.gw.fcubs.ofss.com", "FCUBSCustomerServiceSEI"), FCUBSCustomerServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FCUBSCustomerServiceSEI
     */
    @WebEndpoint(name = "FCUBSCustomerServiceSEI")
    public FCUBSCustomerServiceSEI getFCUBSCustomerServiceSEI(WebServiceFeature... features) {
        return super.getPort(new QName("http://types.ws.gw.fcubs.ofss.com", "FCUBSCustomerServiceSEI"), FCUBSCustomerServiceSEI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FCUBSCUSTOMERSERVICE_EXCEPTION!= null) {
            throw FCUBSCUSTOMERSERVICE_EXCEPTION;
        }
        return FCUBSCUSTOMERSERVICE_WSDL_LOCATION;
    }

}
